apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-server
spec:
  selector:
    matchLabels:
      app: coupon-server
  template:
    metadata:
      labels:
        app: coupon-server
    spec:
      containers:
      - name: coupon-server
        image: core.harbor.domain/coupon/coupon-server:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
