apiVersion: v1
kind: Service
metadata:
  name: prod-coupon-server
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: http
  selector:
    app: prod-coupon-server
