name: Build and Push Docker Images

on:
  push:
    branches:
      - spring
      - nest
  pull_request:
    branches:
      - spring
      - nest
    

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}


jobs:
  springboot-build-push:
    if: github.ref == 'refs/heads/spring'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set timestamp variable
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build and push Spring Boot image
        run: |
          echo "Building Spring Boot image with tag $TIMESTAMP"
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/spring-server:$TIMESTAMP -f spring-server/Dockerfile .
          docker push ${{ env.DOCKERHUB_USERNAME }}/spring-server:$TIMESTAMP

  nestjs-build-push:
    if: github.ref == 'refs/heads/nest'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set timestamp variable
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build and push NestJS image
        run: |
          echo "Building NestJS image with tag $TIMESTAMP"
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/nestjs-server:$TIMESTAMP -f nestjs-server/Dockerfile .
          docker push ${{ env.DOCKERHUB_USERNAME }}/nestjs-server:$TIMESTAMP
